version: '3.4'

services:
  psmoviestore:
    image: psregistrydm.azurecr.io/psmoviestore
    build:
      context: .
      dockerfile: PsMovieStore/Dockerfile
    depends_on:
      - "pspricingapi"
    ports:
      - "80:80"

  pspricingapi:
    image: psregistrydm.azurecr.io/pspricingapi
    build:
      context: .
      dockerfile: PsPricingApi/Dockerfile

